# -*- coding: utf-8 -*-
"""
VNISES Manifesto Film — single source of truth.

Mọi tài liệu (script, storyboard, shot list, EDL, SRT, asset register...) và bản render
offline edit đều được sinh từ file này để bảo đảm nhất quán.

Quy ước thời gian: 25 fps, timecode 00:00:00:00 bắt đầu tại khung hình đầu tiên.
Thời lượng VO là ƯỚC TÍNH (nhịp ~3,75 âm tiết/giây). Khi có VO thu thật, editor conform
lại theo waveform; thứ tự shot, nội dung và transition giữ nguyên.
"""

FPS = 25
VERSION = "v1.0"
TITLE = "VNISES — Manifesto Film"

# ---------------------------------------------------------------------------
# 1. VOICE-OVER
# id, vi, en, rate (âm tiết/giây), gap_after (giây im lặng sau câu), note (biên tập)
# ---------------------------------------------------------------------------
VO = [
    # ACT I — CÂU HỎI
    ("L01", "Có những câu hỏi đã đi cùng con người từ rất lâu.",
     "Some questions have stayed with us for a very long time.", 3.9, 0.8, ""),
    ("L02", "Vũ trụ bắt đầu như thế nào?",
     "How did the universe begin?", 3.8, 0.9, ""),
    ("L03", "Sự sống xuất hiện ra sao?",
     "How did life arise?", 3.8, 0.9, ""),
    ("L04", "Vật chất, không gian và thời gian được tổ chức bởi những quy luật nào?",
     "What laws organize matter, space and time?", 4.1, 0.6, ""),
    ("L05", "Và vị trí của chúng ta trong vũ trụ rộng lớn này là gì?",
     "And what is our place in this vast universe?", 4.0, 1.1, ""),
    # ACT II — KHÁM PHÁ
    ("L06", "Khoa học đã đưa con người tiến rất xa trong việc trả lời những câu hỏi ấy.",
     "Science has taken us a long way toward answering them.", 4.3, 0.35, ""),
    ("L07a", "Chúng ta đã nhìn sâu vào cấu trúc của vật chất,",
     "We have looked deep into the structure of matter,", 4.3, 0.25, ""),
    ("L07b", "đọc được thông tin chứa trong sự sống,",
     "read the information carried by life,", 4.3, 0.25, ""),
    ("L07c", "quan sát ánh sáng đã đi qua vũ trụ hàng tỷ năm,",
     "seen light that crossed the universe over billions of years,", 4.3, 0.25, ""),
    ("L07d", "và đưa thiết bị của mình ra ngoài Trái Đất.",
     "and sent our instruments beyond the Earth.", 4.3, 0.7,
     "Rút gọn nhẹ: 'những thiết bị của mình' → 'thiết bị của mình' (nhịp nói)."),
    ("L08", "Nhưng mỗi khám phá mới lại mở ra những câu hỏi mới.",
     "But every discovery opens new questions.", 4.1, 1.0, ""),
    # ACT III — CON NGƯỜI LÀ MỘT PHẦN CỦA VŨ TRỤ
    ("L09", "Ta thường nói về khám phá vũ trụ như thể đang quan sát một thế giới bên ngoài.",
     "We tend to speak of exploring the universe as if it were a world outside us.", 4.3, 0.7,
     "Rút gọn nhẹ từ baseline (bỏ 'Chúng ta… về việc… mình… ở'); ý giữ nguyên."),
    ("L10", "Nhưng con người chưa bao giờ đứng ngoài tự nhiên.",
     "But we have never stood outside nature.", 3.5, 2.0,
     "Câu then chốt: đọc chậm, nhấn 'chưa bao giờ'; 2 giây im lặng sau câu."),
    ("L11", "Vật chất tạo nên chúng ta cũng là vật chất của vũ trụ.",
     "The matter we are made of is the matter of the universe.", 3.8, 0.8, ""),
    ("L12", "Những quy luật ta tìm cách hiểu cũng chính là quy luật của thế giới ta đang sống.",
     "The laws we try to understand are the laws of the very world we live in.", 4.2, 0.8,
     "Rút gọn nhẹ từ baseline (bỏ lặp 'mà chúng ta', 'trong đó'); ý giữ nguyên."),
    # ACT IV — TRI THỨC QUA NHIỀU THẾ HỆ
    ("L13", "Tri thức khoa học không được tạo nên trong một khoảnh khắc.",
     "Scientific knowledge is not made in a single moment.", 4.2, 0.35, ""),
    ("L14", "Nó được xây dựng qua nhiều thế hệ — từ quan sát, câu hỏi, thí nghiệm, mô hình, dữ liệu, từ những sai lầm được nhận ra và những hiểu biết được sửa lại.",
     "It is built over generations — from observation, questions, experiments, models and data; from mistakes recognized and understanding revised.", 4.4, 0.45,
     "Thêm 'từ' trước 'những sai lầm' để tách nhịp liệt kê; không thêm ý."),
    ("L15", "Mỗi thế hệ tiếp nhận những gì đã có, kiểm tra lại, và bổ sung một phần mới.",
     "Each generation takes what came before, tests it again, and adds something new.", 4.3, 1.1,
     "Rút gọn nhẹ ('kiểm tra lại chúng' → 'kiểm tra lại'; bỏ 'thêm')."),
    # ACT V — VNISES
    ("L16", "VNISES được xây dựng với mong muốn đóng góp một phần vào hành trình ấy.",
     "VNISES was created in the hope of contributing a part to that journey.", 4.0, 1.0, ""),
    # ACT VI — MÔ HÌNH / DỮ LIỆU / TƯƠNG TÁC
    ("L17", "Ở đây, khoa học không chỉ được đọc.",
     "Here, science is not only something to read.", 3.9, 0.5, ""),
    ("L18", "Một hiện tượng có thể được quan sát.",
     "A phenomenon can be observed.", 3.9, 0.8, ""),
    ("L19", "Một mô hình có thể được thay đổi.",
     "A model can be changed.", 3.9, 1.0, ""),
    ("L20", "Một giả định có thể được kiểm tra.",
     "An assumption can be tested.", 3.9, 1.1, ""),
    ("L21", "Một kết quả có thể được so sánh.",
     "A result can be compared.", 3.9, 0.9, ""),
    ("L22", "Và một câu hỏi có thể dẫn sang một câu hỏi sâu hơn.",
     "And one question can lead to a deeper one.", 4.0, 0.9, ""),
    # ACT VII — NEXUS
    ("L23", "Bởi khoa học không tồn tại trong những ngăn riêng biệt.",
     "Because science does not live in separate compartments.", 4.1, 0.5, ""),
    ("L24", "Một câu hỏi về ánh sáng có thể dẫn đến lượng tử, rồi đến thiên văn học.",
     "A question about light can lead to quantum physics, and then to astronomy.", 4.2, 0.6, ""),
    ("L25", "Một bài toán chuyển động có thể dẫn đến quỹ đạo và du hành không gian.",
     "A problem of motion can lead to orbits, and to spaceflight.", 4.2, 0.6, ""),
    ("L26", "Một quan sát về thiên hà có thể mở ra câu hỏi về lịch sử của toàn bộ vũ trụ.",
     "An observation of a galaxy can open questions about the history of the entire universe.", 4.2, 0.8, ""),
    ("L27", "Đó là ý nghĩa của Nexus.",
     "That is what Nexus means.", 3.6, 1.3, "‘Nexus’ đọc /ˈnɛk.səs/ (néc-xợt), không Việt hóa thành ‘nếch-xút’."),
    # ACT VIII — SCIENTIFIC INTEGRITY
    ("L28", "Nhưng khám phá chỉ có ý nghĩa khi đi cùng khả năng kiểm chứng.",
     "But discovery only has meaning when it can be verified.", 4.1, 0.8, ""),
    ("L29", "Dữ liệu cần có nguồn.",
     "Data needs a source.", 3.7, 0.6, ""),
    ("L30", "Mô phỏng phải được phân biệt với quan sát.",
     "Simulation must be distinguished from observation.", 3.9, 0.6, ""),
    ("L31", "Giả định cần được nhận diện.",
     "Assumptions need to be identified.", 3.7, 0.6, ""),
    ("L32", "Giới hạn của mô hình cần được thể hiện.",
     "A model's limits need to be shown.", 3.9, 0.6, ""),
    ("L33", "Và khi chưa có đủ bằng chứng, sự chưa chắc chắn cũng cần được nói rõ.",
     "And when the evidence is not yet enough, the uncertainty must be stated clearly.", 4.1, 1.1, ""),
    ("L34", "VNISES không được xây dựng để làm khoa học trông đơn giản hơn thực tế, cũng không để làm nó phức tạp thêm.",
     "VNISES is not built to make science look simpler than it is — nor to make it more complicated.", 4.3, 0.6,
     "Gộp hai câu baseline thành một để tránh cặp câu đối xứng; ý giữ nguyên."),
    ("L35", "Mục tiêu là làm cho con đường từ quan sát đến hiểu biết trở nên rõ ràng hơn.",
     "The aim is to make the path from observation to understanding clearer.", 4.1, 1.5, ""),
    # ACT IX — NHỮNG ĐIỀU CHƯA BIẾT
    ("L36", "Có thể sẽ luôn còn những câu hỏi vượt quá hiểu biết hiện tại của chúng ta.",
     "There may always be questions beyond what we currently understand.", 3.8, 0.9, ""),
    ("L37", "Và chính vì thế, hành trình khám phá vẫn tiếp tục.",
     "And that is why the journey of discovery continues.", 3.5, 1.2,
     "Kết câu hạ giọng tự nhiên, không ngân."),
    # ACT X — VNISES
    ("L38", "VNISES. Vietnam Nexus for Interactive Space Exploration and Science.",
     "VNISES. Vietnam Nexus for Interactive Space Exploration and Science.", 3.3, 2.0,
     "Đọc tên mở rộng bằng tiếng Anh chuẩn, chậm, không nhấn kiểu quảng cáo."),
]

# Khoảng lặng trước câu đầu tiên (màn hình tối → ảnh mở dần)
LEAD_IN = 1.5
# Tiếng Anh trong câu được tính theo âm tiết ước lượng
EN_SYLLABLE_OVERRIDE = {"L38": 18}
# Phần đuôi sau câu cuối: giữ logo + thẻ credit
TAIL = 5.0

# ---------------------------------------------------------------------------
# 2. ASSETS
# layer: A = real scientific asset, B = VNISES product footage, C = in-house motion graphics
# status: VERIFY = nguồn/licence cần xác minh trước khi tải (môi trường sản xuất không truy cập được);
#         TO SELECT = cần chọn đúng file trong bộ sưu tập; CAPTURED = đã có trong gói;
#         TO CAPTURE = cần quay; IN-HOUSE = đã dựng trong gói.
# ---------------------------------------------------------------------------
ASSETS = [
    dict(id="A01", layer="A", desc="Ảnh chụp bầu trời đêm (dải Ngân Hà) trên một đài quan sát của ESO ở Chile, có công trình kính thiên văn trong khung hình",
         source="ESO Image Archive", org="ESO (European Southern Observatory)", url="https://www.eso.org/public/images/",
         license="CC BY 4.0 (theo chính sách ảnh công khai của ESO; xác nhận trên trang của từng ảnh)",
         credit="ESO/<tên nhiếp ảnh gia theo trang ảnh>", status="TO SELECT + VERIFY",
         note="Chọn ảnh chụp thật (không phải ảnh ghép), phơi sáng tự nhiên, không xử lý màu quá mức. Ghi đúng mã ảnh ESO khi tải."),
    dict(id="A02", layer="A", desc="Bản đồ toàn bầu trời bức xạ nền vi sóng vũ trụ (CMB) của vệ tinh Planck",
         source="ESA Multimedia — Planck", org="ESA and the Planck Collaboration", url="https://www.esa.int/ESA_Multimedia/Images (tìm: Planck CMB)",
         license="ESA Standard Licence hoặc CC BY-SA 3.0 IGO tùy ảnh — kiểm tra trên trang ảnh",
         credit="ESA and the Planck Collaboration", status="TO SELECT + VERIFY",
         note="Dùng bản đồ chính thức (phép chiếu Mollweide), không tô màu lại."),
    dict(id="A03", layer="A", desc="Ảnh stromatolite (cấu trúc do vi sinh vật tạo thành), ví dụ Hamelin Pool, vịnh Shark (Tây Úc)",
         source="Kho ảnh của cơ quan khoa học/địa chất (ưu tiên USGS, Geoscience Australia) hoặc Wikimedia Commons có licence rõ ràng",
         org="UNKNOWN — chọn khi tải", url="UNKNOWN",
         license="UNKNOWN — chỉ dùng nếu PD, CC0 hoặc CC BY",
         credit="Theo nguồn được chọn", status="UNKNOWN — TO SELECT",
         note="Phương án thay thế nếu không có licence rõ: ảnh vệ tinh Trái Đất (NASA, public domain) cho câu 'Sự sống xuất hiện ra sao?'."),
    dict(id="A04", layer="A", desc="Event display va chạm proton–proton thật từ thí nghiệm CMS hoặc ATLAS tại LHC",
         source="CERN Document Server (cds.cern.ch)", org="CERN / CMS Collaboration hoặc ATLAS Collaboration", url="https://cds.cern.ch/",
         license="CERN: phần lớn ảnh công bố theo CC BY 4.0 — kiểm tra từng bản ghi",
         credit="CERN / CMS Collaboration (hoặc ATLAS Experiment © CERN theo bản ghi)", status="TO SELECT + VERIFY",
         note="Chọn event display đã được thí nghiệm công bố chính thức; không dùng ảnh minh họa nghệ thuật."),
    dict(id="A05", layer="A", desc="Hubble Ultra Deep Field (2004)",
         source="ESA/Hubble — heic0406a", org="NASA, ESA, S. Beckwith (STScI) and the HUDF Team", url="https://esahubble.org/images/heic0406a/",
         license="CC BY 4.0 (ESA/Hubble)", credit="NASA, ESA, S. Beckwith (STScI) and the HUDF Team", status="VERIFY",
         note="Dùng bản full-resolution; push-in chậm không quá 1,15×."),
    dict(id="A06", layer="A", desc="Ảnh kính hiển vi quét xuyên hầm (STM) cho thấy từng nguyên tử trên bề mặt tinh thể",
         source="NIST (U.S. National Institute of Standards and Technology) — kho ảnh", org="NIST", url="https://www.nist.gov/",
         license="Tác phẩm của chính phủ Hoa Kỳ thường thuộc public domain — xác nhận ảnh không do bên thứ ba giữ bản quyền",
         credit="NIST", status="TO SELECT + VERIFY",
         note="Chú thích phải nói rõ đây là ảnh STM (dữ liệu dòng xuyên hầm được hiển thị thành ảnh), không phải 'ảnh chụp' quang học."),
    dict(id="A07", layer="A", desc="Biểu đồ giải trình tự DNA (chromatogram) hoặc ảnh thiết bị giải trình tự",
         source="NHGRI — genome.gov image gallery", org="National Human Genome Research Institute", url="https://www.genome.gov/",
         license="Public domain (U.S. Government) — xác nhận trên trang ảnh",
         credit="Courtesy: National Human Genome Research Institute", status="TO SELECT + VERIFY",
         note="Không dùng hình DNA phát sáng 3D. Chromatogram là dữ liệu đo thật."),
    dict(id="A08", layer="A", desc="Ảnh Hubble của cụm thiên hà SMACS 0723 (chương trình RELICS)",
         source="ESA/Hubble", org="ESA/Hubble & NASA, RELICS", url="https://esahubble.org/images/ (tìm: SMACS 0723)",
         license="CC BY 4.0 (ESA/Hubble)", credit="ESA/Hubble & NASA, RELICS", status="TO SELECT + VERIFY",
         note="Phải cùng trường nhìn với A10 để làm phép so sánh ở SH10. Căn chỉnh (register) hai ảnh theo các sao/thiên hà sáng."),
    dict(id="A09", layer="A", desc="Ảnh chụp gương chính của Kính viễn vọng James Webb trong phòng sạch",
         source="NASA Image and Video Library", org="NASA (ảnh của Chris Gunn hoặc nhiếp ảnh gia NASA khác)", url="https://images.nasa.gov/ (tìm: Webb primary mirror cleanroom)",
         license="Public domain theo NASA Media Usage Guidelines (không dùng logo NASA, không ngụ ý NASA bảo trợ)",
         credit="NASA/<nhiếp ảnh gia>", status="TO SELECT + VERIFY",
         note="Ảnh chụp thật — không dùng ảnh render của tàu trong không gian (là hình minh họa)."),
    dict(id="A10", layer="A", desc="Webb's First Deep Field — SMACS 0723 (NIRCam, công bố 07/2022)",
         source="STScI / webbtelescope.org; ESA/Webb", org="NASA, ESA, CSA, STScI", url="https://webbtelescope.org/ (tìm: Webb's First Deep Field)",
         license="NASA: public domain theo hướng dẫn sử dụng; ESA/Webb: CC BY 4.0 — kiểm tra trên trang ảnh",
         credit="NASA, ESA, CSA, STScI", status="VERIFY",
         note="Wipe so sánh với A08 phải giữ nguyên tỉ lệ và căn chỉnh."),
    dict(id="A11", layer="A", desc="Earthrise — Apollo 8, 24/12/1968, ảnh AS08-14-2383",
         source="NASA Image and Video Library", org="NASA (ảnh chụp bởi phi hành gia William Anders)", url="https://images.nasa.gov/ (tìm: AS08-14-2383)",
         license="Public domain theo NASA Media Usage Guidelines", credit="NASA / Apollo 8 — William Anders", status="VERIFY",
         note="Dùng bản scan gốc định hướng theo bản lưu trữ; không xoay/tô màu lại."),
    dict(id="A12", layer="A", desc="Pale Blue Dot Revisited (2020) — ảnh Voyager 1 năm 1990 được xử lý lại",
         source="NASA/JPL Photojournal — PIA23645", org="NASA/JPL-Caltech", url="https://photojournal.jpl.nasa.gov/catalog/PIA23645",
         license="Public domain theo chính sách của NASA/JPL (ghi credit)", credit="NASA/JPL-Caltech", status="VERIFY",
         note="Chú thích nên ghi 'Voyager 1, 1990 — xử lý lại năm 2020'. Không tăng độ sáng điểm Trái Đất."),
    dict(id="A13", layer="A", desc="Hình vẽ Mặt Trăng của Galileo Galilei — Sidereus Nuncius (1610)",
         source="Bản scan từ thư viện có chính sách mở (ví dụ Library of Congress, e-rara.ch)", org="Galileo Galilei (1610); thư viện lưu trữ", url="https://www.loc.gov/ hoặc https://www.e-rara.ch/ (tìm: Sidereus Nuncius)",
         license="Tác phẩm thuộc public domain; chính sách sử dụng bản scan tùy thư viện — kiểm tra",
         credit="Galileo Galilei, Sidereus Nuncius (1610) — <tên thư viện>", status="TO SELECT + VERIFY",
         note="Không dùng bản scan có licence phi thương mại (NC)."),
    dict(id="A14", layer="A", desc="Hình quỹ đạo sao Hỏa trong Astronomia Nova của Johannes Kepler (1609)",
         source="Bản scan thư viện có chính sách mở", org="Johannes Kepler (1609); thư viện lưu trữ", url="https://www.e-rara.ch/ hoặc https://www.loc.gov/ (tìm: Astronomia nova)",
         license="Tác phẩm thuộc public domain; kiểm tra chính sách bản scan", credit="Johannes Kepler, Astronomia Nova (1609) — <tên thư viện>", status="TO SELECT + VERIFY",
         note=""),
    dict(id="A15", layer="A", desc="Trang/hình trong Philosophiæ Naturalis Principia Mathematica của Isaac Newton (1687)",
         source="Bản scan thư viện có chính sách mở", org="Isaac Newton (1687); thư viện lưu trữ", url="https://www.loc.gov/ hoặc https://www.e-rara.ch/ (tìm: Principia 1687)",
         license="Tác phẩm thuộc public domain; tránh bản scan CC BY-NC (ví dụ một số bộ sưu tập số của đại học)", credit="Isaac Newton, Principia (1687) — <tên thư viện>", status="TO SELECT + VERIFY",
         note=""),
    dict(id="A16", layer="A", desc="Biểu đồ vận tốc – khoảng cách của Edwin Hubble (PNAS, 1929)",
         source="Proceedings of the National Academy of Sciences 15(3):168–173, doi:10.1073/pnas.15.3.168", org="Edwin Hubble (1929)", url="https://doi.org/10.1073/pnas.15.3.168",
         license="Public domain tại Hoa Kỳ (xuất bản 1929, hết hạn 01/01/2025); tác giả mất 1953 — hết hạn ở các nước áp dụng thời hạn đời tác giả + 70 năm. Xác nhận với tư vấn pháp lý nếu phát hành thương mại.",
         credit="E. Hubble, PNAS 15 (1929)", status="VERIFY",
         note="Ví dụ thật về hiểu biết được sửa lại: giá trị hằng số giãn nở Hubble ước tính năm 1929 (~500 km/s/Mpc) lớn gấp khoảng 7 lần các giá trị hiện nay (~67–73)."),
    # Layer B — VNISES product footage
    dict(id="B01", layer="B", desc="Module giới thiệu VNISES — cuộn từ tiêu đề tới hình quỹ đạo Kepler đang chuyển động (scene 01)",
         source="vnises-gioithieu.php v1.0 (commit 9d59dd4), render cục bộ", org="VNISES", url="repo vankhangtrinh/vnises_gt",
         license="Sở hữu của VNISES", credit="—", status="CAPTURED (offline edit) — RE-CAPTURE trên vnises.com sau khi triển khai",
         note="Module đã được xây dựng nhưng CHƯA xác nhận đang chạy trên vnises.com. Không phát hành bản master nếu module chưa lên site."),
    dict(id="B02", layer="B", desc="Phòng thí nghiệm độ lệch tâm — kéo thanh trượt e từ 0,10 lên 0,70",
         source="vnises-gioithieu.php v1.0, scene 04", org="VNISES", url="repo vankhangtrinh/vnises_gt",
         license="Sở hữu của VNISES", credit="—", status="CAPTURED (offline edit) — RE-CAPTURE trên vnises.com", note="SIMULATION, có nhãn trên UI."),
    dict(id="B03", layer="B", desc="Phòng thí nghiệm độ lệch tâm — ghim quỹ đạo tham chiếu rồi thay đổi e để so sánh",
         source="vnises-gioithieu.php v1.0, scene 04", org="VNISES", url="repo vankhangtrinh/vnises_gt",
         license="Sở hữu của VNISES", credit="—", status="CAPTURED (offline edit) — RE-CAPTURE trên vnises.com", note=""),
    dict(id="B04", layer="B", desc="Khối 'Một câu hỏi, nhiều hướng đi' trong scene Nexus của module giới thiệu",
         source="vnises-gioithieu.php v1.0, scene 03", org="VNISES", url="repo vankhangtrinh/vnises_gt",
         license="Sở hữu của VNISES", credit="—", status="CAPTURED (offline edit) — RE-CAPTURE trên vnises.com", note=""),
    dict(id="B05", layer="B", desc="Sơ đồ Nexus tương tác — chọn lần lượt các khái niệm",
         source="vnises-gioithieu.php v1.0, scene 03", org="VNISES", url="repo vankhangtrinh/vnises_gt",
         license="Sở hữu của VNISES", credit="—", status="CAPTURED (offline edit) — RE-CAPTURE trên vnises.com", note=""),
    dict(id="B06", layer="B", desc="Chuỗi phương pháp 'Quan sát → Thay đổi → So sánh → Kiểm chứng → Hiểu' và bảng provenance",
         source="vnises-gioithieu.php v1.0, scene 04 & 07", org="VNISES", url="repo vankhangtrinh/vnises_gt",
         license="Sở hữu của VNISES", credit="—", status="CAPTURED (offline edit) — RE-CAPTURE trên vnises.com", note=""),
    dict(id="B07", layer="B", desc="(Tùy chọn, nâng cấp) Module quan sát Mặt Trời / Trạm Vũ trụ trên vnises.com hiển thị ảnh SDO thật kèm nguồn",
         source="vnises.com — Trạm Vũ trụ", org="VNISES (dữ liệu: NASA/SDO)", url="https://vnises.com",
         license="UI: VNISES; ảnh SDO: theo chính sách dữ liệu SDO (ghi credit 'Courtesy of NASA/SDO and the AIA, EVE, and HMI science teams')",
         credit="Courtesy of NASA/SDO and the AIA, EVE, and HMI science teams", status="TO CAPTURE — chỉ khi module đang hoạt động",
         note="Nếu dùng: thay B01 ở SH18 (câu 'Một hiện tượng có thể được quan sát'). Phải hiển thị nguồn và thời điểm dữ liệu đúng như UI thật, không dựng lại."),
    # Layer C — in-house motion graphics (rendered by this package)
    dict(id="C01", layer="C", desc="Các nguyên tố chính trong cơ thể người và nguồn gốc của chúng", source="Dựng trong gói (film/src/render)", org="VNISES", url="—", license="Sở hữu của VNISES", credit="—", status="IN-HOUSE", note="Không dùng số phần trăm; chỉ phân loại nguồn gốc."),
    dict(id="C02", layer="C", desc="Khẩu pháo của Newton — quỹ đạo tính bằng tích phân số (mô hình hấp dẫn Newton)", source="Dựng trong gói", org="VNISES", url="—", license="Sở hữu của VNISES", credit="—", status="IN-HOUSE", note="SIMULATION; Trái Đất vẽ dạng sơ đồ, độ cao núi phóng đại."),
    dict(id="C03", layer="C", desc="Mạng tri thức tích lũy qua nhiều thế hệ → hội tụ thành VNISES", source="Dựng trong gói", org="VNISES", url="—", license="Sở hữu của VNISES", credit="—", status="IN-HOUSE", note="Bố cục tất định, không ngẫu nhiên."),
    dict(id="C04", layer="C", desc="Lộ diện VNISES", source="Dựng trong gói", org="VNISES", url="—", license="Sở hữu của VNISES", credit="—", status="IN-HOUSE", note=""),
    dict(id="C05", layer="C", desc="Kiểm tra giả định: quỹ đạo vật ném có/không có lực cản không khí", source="Dựng trong gói", org="VNISES", url="—", license="Sở hữu của VNISES", credit="—", status="IN-HOUSE", note="SIMULATION; định tính, không đơn vị."),
    dict(id="C06", layer="C", desc="Mạng Nexus xây dần theo ba chuỗi liên kết", source="Dựng trong gói", org="VNISES", url="—", license="Sở hữu của VNISES", credit="—", status="IN-HOUSE", note=""),
    dict(id="C07", layer="C", desc="Sơ đồ phân loại thông tin: OBSERVATION / DATA / SIMULATION / ASSUMPTION / INFERENCE + SOURCE / CONDITIONS / LIMITATIONS", source="Dựng trong gói", org="VNISES", url="—", license="Sở hữu của VNISES", credit="—", status="IN-HOUSE", note="Sơ đồ khái niệm, không có số liệu."),
    dict(id="C08", layer="C", desc="End card VNISES + credit hình ảnh", source="Dựng trong gói", org="VNISES", url="—", license="Sở hữu của VNISES", credit="—", status="IN-HOUSE", note=""),
]

# ---------------------------------------------------------------------------
# 3. SHOTS
# vo: danh sách id câu VO nằm trong shot (shot bắt đầu `lead` giây trước câu đầu tiên).
# trans_in: transition VÀO shot này. "cut" | "dissolve:<giây>" | "dip:<giây>" (qua màu đen)
# ---------------------------------------------------------------------------
SHOTS = [
    dict(id="SH01", act="I · Câu hỏi", vo=["L01"], start=0.0, layer="A", assets=["A01"],
         visual="Bầu trời đêm thật trên đài quan sát. Khung hình rộng, đường chân trời ở 1/4 dưới. Ảnh mở dần từ màn đen.",
         motion="Push-in 1,00× → 1,05× tuyến tính suốt shot. Không xoay.",
         trans_in="fade from black 1,6 s", onscreen="Credit nhỏ góc dưới trái (giây 1,5–4,5 của shot): 'Ảnh: ESO/<tác giả theo trang ảnh>'.",
         audio="Room tone rất thấp; drone nền bắt đầu ở −36 LUFS, không có giai điệu.",
         sci="OBSERVATION — ảnh chụp thật. Không chồng thêm sao/ánh sáng.",
         lic="CC BY 4.0 → bắt buộc credit trên màn hình hoặc trong credit cuối."),
    dict(id="SH02", act="I · Câu hỏi", vo=["L02"], layer="A", assets=["A02"],
         visual="Bản đồ CMB của Planck (phép chiếu Mollweide) đặt giữa nền đen, chiếm ~70% chiều ngang.",
         motion="Tĩnh, scale 1,00 → 1,03.", trans_in="dissolve:0.8",
         onscreen="Credit nhỏ: 'Bức xạ nền vi sóng vũ trụ — ESA và Planck Collaboration'.",
         audio="Nền giữ nguyên.",
         sci="DATA — bản đồ đã xử lý từ quan sát, cho thấy dao động nhiệt độ rất nhỏ của bức xạ phát ra khoảng 380.000 năm sau Big Bang. Không gọi là 'ảnh chụp khoảnh khắc Big Bang'.",
         lic="Kiểm tra ESA licence của đúng ảnh tải về."),
    dict(id="SH03", act="I · Câu hỏi", vo=["L03"], layer="A", assets=["A03"],
         visual="Stromatolite ở vùng nước nông, ánh sáng tự nhiên, cận cảnh trung bình.",
         motion="Pan ngang rất chậm (2% chiều rộng).", trans_in="dissolve:0.8",
         onscreen="Credit nhỏ theo nguồn được chọn.", audio="Nền giữ nguyên.",
         sci="OBSERVATION. Stromatolite hiện đại là cấu trúc tương tự với những dấu vết sự sống cổ nhất; không nói đây là 'sự sống đầu tiên'.",
         lic="UNKNOWN cho tới khi chọn ảnh — xem phương án thay thế trong A03."),
    dict(id="SH04", act="I · Câu hỏi", vo=["L04"], layer="A", assets=["A04"],
         visual="Event display va chạm proton–proton trong detector của LHC — các vết hạt tỏa ra từ tâm.",
         motion="Push-in chậm vào điểm va chạm 1,00 → 1,08.", trans_in="dissolve:0.8",
         onscreen="Credit nhỏ: 'CERN / <tên thí nghiệm>'.", audio="Nền giữ nguyên.",
         sci="DATA — tái dựng sự kiện từ tín hiệu detector. Nếu là 'Higgs candidate' thì gọi đúng là ứng viên.",
         lic="Xác nhận CC BY 4.0 trên bản ghi CDS."),
    dict(id="SH05", act="I–II · Câu hỏi → Khám phá", vo=["L05", "L06"], layer="A", assets=["A05"],
         visual="Hubble Ultra Deep Field — hàng nghìn thiên hà. Giữ lâu để người xem nhìn.",
         motion="Push-in rất chậm 1,00 → 1,12 qua cả hai câu VO.", trans_in="dissolve:1.0",
         onscreen="Credit nhỏ: 'NASA, ESA, S. Beckwith (STScI) và HUDF Team'.", audio="Nền mở rộng nhẹ một bè (pad thấp) ở câu L06.",
         sci="OBSERVATION. Gần như mọi điểm sáng là một thiên hà; ánh sáng của các thiên hà xa nhất đã đi hơn 13 tỷ năm.",
         lic="CC BY 4.0 — credit bắt buộc."),
    dict(id="SH06", act="II · Khám phá", vo=["L07a"], layer="A", assets=["A06"],
         visual="Ảnh STM các nguyên tử trên bề mặt tinh thể — lưới đều đặn.",
         motion="Tĩnh, scale 1,00 → 1,02.", trans_in="cut",
         onscreen="Credit nhỏ: 'Ảnh STM — NIST'.", audio="Một nốt 'data tone' rất nhẹ ở đầu shot (−30 dB so với VO).",
         sci="DATA — ảnh dựng từ dòng xuyên hầm, không phải ảnh quang học.", lic="Xác nhận PD."),
    dict(id="SH07", act="II · Khám phá", vo=["L07b"], layer="A", assets=["A07"],
         visual="Chromatogram giải trình tự DNA — các đỉnh màu theo thứ tự base.",
         motion="Pan ngang chậm theo chiều đọc trình tự.", trans_in="cut",
         onscreen="Credit nhỏ: 'NHGRI'.", audio="Nền.",
         sci="DATA — tín hiệu đo của máy giải trình tự.", lic="Xác nhận PD."),
    dict(id="SH08", act="II · Khám phá", vo=["L07c"], layer="A", assets=["A08"],
         visual="Ảnh Hubble của cụm SMACS 0723.",
         motion="Tĩnh, đặt sẵn khung để khớp với SH10.", trans_in="cut",
         onscreen="Credit nhỏ: 'ESA/Hubble & NASA, RELICS'.", audio="Nền.",
         sci="OBSERVATION.", lic="CC BY 4.0."),
    dict(id="SH09", act="II · Khám phá", vo=["L07d"], layer="A", assets=["A09"],
         visual="Gương chính của JWST trong phòng sạch — thấy kỹ sư để cảm nhận tỉ lệ (người thật, ảnh thật).",
         motion="Tilt nhẹ từ dưới lên.", trans_in="cut",
         onscreen="Credit nhỏ: 'NASA/<nhiếp ảnh gia>'.", audio="Nền.",
         sci="Ảnh chụp thật của thiết bị.", lic="NASA PD — không dùng logo NASA."),
    dict(id="SH10", act="II · Khám phá", vo=["L08"], layer="A", assets=["A08", "A10"],
         visual="Trở lại cùng trường nhìn SMACS 0723: wipe dọc chậm từ ảnh Hubble sang ảnh Webb — nhiều thiên hà mờ và cung thấu kính hấp dẫn xuất hiện.",
         motion="Wipe trái → phải trong 3,5 s, đường wipe là một vạch mảnh 1 px màu trung tính. Sau wipe giữ tĩnh.",
         trans_in="cut", onscreen="Nhãn nhỏ hai bên đường wipe: 'Hubble' / 'Webb'. Credit cả hai nguồn.",
         audio="Nền hạ nhẹ trong khoảng lặng sau câu.",
         sci="OBSERVATION. So sánh hợp lệ chỉ khi hai ảnh được căn chỉnh đúng; khác biệt do độ nhạy và bước sóng hồng ngoại.",
         lic="A08 CC BY 4.0; A10 theo nguồn tải."),
    dict(id="SH11", act="III · Con người là một phần của vũ trụ", vo=["L09"], layer="A", assets=["A11"],
         visual="Earthrise — Trái Đất trên đường chân trời Mặt Trăng.",
         motion="Tĩnh, scale 1,00 → 1,04.", trans_in="dip:1.0",
         onscreen="Credit nhỏ: 'NASA / Apollo 8 — William Anders, 1968'.", audio="Nhạc rút còn một bè.",
         sci="OBSERVATION.", lic="NASA PD."),
    dict(id="SH12", act="III · Con người là một phần của vũ trụ", vo=["L10"], layer="A", assets=["A12"],
         visual="Pale Blue Dot — Trái Đất là một điểm sáng rất nhỏ trong vệt sáng tán xạ. Khung rộng, điểm Trái Đất ở 1/3 phải.",
         motion="Push-in rất chậm 1,00 → 1,10 hướng về điểm Trái Đất; tiếp tục trong 2 giây im lặng sau câu.",
         trans_in="dissolve:1.6",
         onscreen="Credit nhỏ: 'Voyager 1, 1990 — NASA/JPL-Caltech (xử lý lại năm 2020)'.",
         audio="2 giây chỉ còn room tone + một nốt trầm duy nhất.",
         sci="OBSERVATION. Không làm sáng thêm điểm Trái Đất; không thêm vòng tròn chỉ dẫn.",
         lic="NASA/JPL PD — credit."),
    dict(id="SH13", act="III · Con người là một phần của vũ trụ", vo=["L11"], layer="C", assets=["C01"],
         visual="Nền đen. Sáu ký hiệu nguyên tố xuất hiện lần lượt: H, O, C, N, Ca, P. Hai đường mảnh nối về hai nhãn nguồn gốc: H → 'vũ trụ sơ khai'; O C N Ca P → 'các ngôi sao và vụ nổ sao'.",
         motion="Mỗi ký hiệu fade-in 0,6 s, cách nhau 0,35 s; đường nối vẽ dần 1,2 s.", trans_in="dissolve:1.2",
         onscreen="Các ký hiệu + hai nhãn nguồn gốc (xem 09_Motion_Graphics_Spec).",
         audio="Nốt trầm từ SH12 kéo dài; thêm một hòa âm thứ hai rất nhẹ.",
         sci="FACT: hydro hình thành chủ yếu trong vài phút đầu của vũ trụ; C, N, O, Ca, P hình thành chủ yếu trong các ngôi sao và vụ nổ sao. Không nói 'mọi nguyên tử đều từ sao'. Không dùng tỉ lệ phần trăm.",
         lic="In-house."),
    dict(id="SH14", act="III · Con người là một phần của vũ trụ", vo=["L12"], layer="C", assets=["C02"],
         visual="Khẩu pháo của Newton: một cung tròn (Trái Đất, sơ đồ), một ngọn núi phóng đại; các quỹ đạo vật ném với vận tốc tăng dần — rơi xuống gần, rơi xa hơn, rồi vòng quanh thành quỹ đạo.",
         motion="Mỗi quỹ đạo vẽ dần theo thời gian thực của mô phỏng; quỹ đạo cuối khép kín.",
         trans_in="dissolve:0.8", onscreen="Nhãn nhỏ góc trên: 'SIMULATION · cùng một định luật hấp dẫn'.",
         audio="Nền ổn định.",
         sci="SIMULATION — tích phân số định luật hấp dẫn Newton cho vật ném từ độ cao h (phóng đại để nhìn thấy). Quỹ đạo tròn đạt khi v = √(GM/r).",
         lic="In-house. Ý tưởng theo hình gốc của Newton (1728, public domain)."),
    dict(id="SH15", act="IV · Tri thức qua nhiều thế hệ", vo=["L13", "L14"], layer="A", assets=["A13", "A14", "A15", "A16"],
         visual="Bàn tư liệu: bốn trang tư liệu thật đặt cạnh nhau theo thời gian — Galileo 1610 (quan sát), Kepler 1609 (mô hình quỹ đạo), Newton 1687 (định luật), Hubble 1929 (dữ liệu). Năm in nhỏ dưới mỗi trang.",
         motion="Camera trượt ngang rất chậm từ trái sang phải trong toàn shot; dừng ở biểu đồ Hubble 1929 khi VO nói 'những hiểu biết được sửa lại'.",
         trans_in="dip:0.8",
         onscreen="Năm dưới mỗi tư liệu. Tại biểu đồ Hubble: chú thích nhỏ 'Hằng số giãn nở ước tính năm 1929 lớn gấp khoảng 7 lần giá trị ngày nay.'",
         audio="Tiếng giấy rất nhẹ ở đầu shot (tùy chọn); nền.",
         sci="FACT: Hubble (1929) ước tính ~500 km/s/Mpc; giá trị hiện nay ~67–73 km/s/Mpc. Ví dụ thật của hiểu biết được sửa lại.",
         lic="Public domain; kiểm tra chính sách bản scan."),
    dict(id="SH16", act="IV → V", vo=["L15"], layer="C", assets=["C03"],
         visual="Bốn tư liệu thu nhỏ thành bốn điểm. Các điểm mới xuất hiện theo từng lớp (mỗi lớp là một thế hệ), mỗi điểm nối về điểm cũ. Mạng lưới lớn dần, đều đặn, không ngẫu nhiên.",
         motion="Mỗi lớp xuất hiện sau 1,1 s; đường nối vẽ dần.", trans_in="dissolve:1.0",
         onscreen="Không chữ.", audio="Nhạc bắt đầu mở: thêm một bè cao rất nhẹ.",
         sci="CONCEPTUAL — sơ đồ minh họa tính kế thừa, không biểu diễn dữ liệu.", lic="In-house."),
    dict(id="SH17", act="V · VNISES", vo=["L16"], layer="C", assets=["C04"],
         visual="Mạng lưới lắng xuống thành hình học đều; một điểm ở trung tâm sáng lên màu vàng ấm. 'VNISES' hiện ở giữa; tên đầy đủ hiện bên dưới sau 1 s.",
         motion="Wordmark fade-in 1,2 s + tracking giảm nhẹ (0,08em → 0,04em). Không scale, không flare.", trans_in="cut",
         onscreen="VNISES / Vietnam Nexus for Interactive Space Exploration and Science",
         audio="Điểm mở rộng duy nhất của nhạc trong phim — một hợp âm mở, không trống, không boom.",
         sci="—", lic="In-house."),
    dict(id="SH18", act="VI · Mô hình / dữ liệu / tương tác", vo=["L17", "L18"], layer="B", assets=["B01", "B07"],
         visual="Footage thật của VNISES: trang giới thiệu cuộn từ tiêu đề 'Khoa học trở nên gần gũi hơn…' xuống hình quỹ đạo Kepler đang chuyển động (nhãn SIMULATION hiện trên UI).",
         motion="Camera giữ ở tiêu đề 1,0 s, trượt có easing tới hình quỹ đạo (1,0–3,4 s), sau đó push-in 1,00 → 1,55 vào hình (3,2–5,8 s). UI vector nên push-in không vỡ hình khi quay ở DPR 2.",
         trans_in="dissolve:0.6", onscreen="Không thêm chữ ngoài UI.", audio="Nhạc giữ; không tiếng click giả.",
         sci="SIMULATION, được UI gắn nhãn đúng. Nếu B07 (quan sát Mặt Trời thật) có trên vnises.com thì thay cho câu L18.",
         lic="VNISES."),
    dict(id="SH19", act="VI · Mô hình / dữ liệu / tương tác", vo=["L19"], layer="B", assets=["B02"],
         visual="Phòng thí nghiệm độ lệch tâm: thanh trượt e di chuyển từ 0,10 lên 0,70; elip dẹt dần, các điểm cách đều theo thời gian dồn về viễn điểm.",
         motion="Khung cố định zoom 1,25 vào khối lab (thấy nhãn SIMULATION, hình, thanh trượt, bảng số). Con trỏ kéo e 0,10 → 0,70 trong 0,35–2,5 s, có easing.", trans_in="cut",
         onscreen="Không.", audio="Nền.", sci="SIMULATION (Kepler, a cố định).", lic="VNISES."),
    dict(id="SH20", act="VI · Mô hình / dữ liệu / tương tác", vo=["L20"], layer="C", assets=["C05"],
         visual="Một quỹ đạo vật ném với nhãn ASSUMPTION 'bỏ qua lực cản không khí'. Bật điều kiện có lực cản: đường thứ hai hiện ra ngắn hơn, thấp hơn, không đối xứng.",
         motion="Đường 1 vẽ dần 1,4 s; nhãn giả định gạch đi; đường 2 vẽ dần 1,4 s.", trans_in="cut",
         onscreen="'ASSUMPTION · bỏ qua lực cản không khí' → 'có lực cản không khí'.", audio="Nền.",
         sci="SIMULATION định tính: lực cản tỉ lệ v² làm tầm xa giảm và nhánh rơi dốc hơn nhánh lên.", lic="In-house."),
    dict(id="SH21", act="VI · Mô hình / dữ liệu / tương tác", vo=["L21"], layer="B", assets=["B03"],
         visual="Phòng thí nghiệm độ lệch tâm: ghim quỹ đạo e = 0,30 làm tham chiếu (nét đứt), kéo e lên 0,75; các tỉ số trong bảng thay đổi.",
         motion="Khung như SH19. Con trỏ di tới nút 'Ghim làm quỹ đạo tham chiếu', bấm ở 0,6 s, quay lại thanh trượt và kéo e 0,30 → 0,75 trong 1,05–2,6 s.", trans_in="cut",
         onscreen="Không.", audio="Nền.", sci="SIMULATION; các tỉ số được tính đúng từ e.", lic="VNISES."),
    dict(id="SH22", act="VI · Mô hình / dữ liệu / tương tác", vo=["L22"], layer="B", assets=["B04"],
         visual="Khối 'Ví dụ: một câu hỏi, nhiều hướng đi' — câu hỏi 'Vì sao vệ tinh không rơi xuống Trái Đất?' và bốn nhánh.",
         motion="Zoom 1,85 vào cột phải; trượt dọc chậm từ câu hỏi xuống nhánh cuối (0,2–4,2 s). Matte tối mép trái che phần sơ đồ không liên quan.", trans_in="cut", onscreen="Không.", audio="Nền.",
         sci="Nội dung nhánh đúng vật lý (vệ tinh liên tục rơi nhưng có vận tốc ngang đủ lớn).", lic="VNISES."),
    dict(id="SH23", act="VII · Nexus", vo=["L23", "L24", "L25", "L26"], layer="C", assets=["C06"],
         visual="Nền graphite. Mở đầu: các lĩnh vực nằm trong những ô ngăn cách bởi vạch mảnh; vạch mờ đi. Sau đó ba chuỗi liên kết lần lượt hình thành thành ba hàng ngang theo từng câu VO.",
         motion="Mỗi chuỗi: nút xuất hiện 0,4 s/nút, đường nối vẽ dần. Không chuyển động tự do của nút.",
         trans_in="dip:0.8",
         onscreen="Nhãn nút (tiếng Việt): Ánh sáng → Thế giới tự nhiên → Lượng tử → Thiên văn học · Chuyển động → Cơ học → Quỹ đạo → Du hành không gian · Quan sát thiên hà → Vũ trụ học → Lịch sử vũ trụ.",
         audio="Nhạc có một chuyển động hòa âm nhẹ ở mỗi chuỗi mới.",
         sci="Các liên kết đúng: phổ ánh sáng ↔ lượng tử ↔ quang phổ thiên văn; cơ học Newton ↔ quỹ đạo ↔ du hành không gian; quan sát thiên hà ↔ vũ trụ học.",
         lic="In-house."),
    dict(id="SH24", act="VII · Nexus", vo=["L27"], layer="C", assets=["C06", "B05"],
         visual="Các liên kết chéo vàng nối ba chuỗi (Thế giới tự nhiên ↔ Cơ học; Quỹ đạo ↔ Thiên văn học; Lượng tử ↔ Vũ trụ học; Thiên văn học ↔ Lịch sử vũ trụ) — các 'ngăn' không còn tách biệt. Dissolve sang sơ đồ Nexus thật của VNISES, một khái niệm được chọn.",
         motion="Liên kết chéo vẽ dần 0–1,5 s; dissolve 0,6 s sang footage sơ đồ Nexus thật; con trỏ chọn 'Mô hình' (≈2,4 s của shot).", trans_in="cut",
         onscreen="Nhãn 'NEXUS · điểm hội tụ giữa các lĩnh vực' góc trên trái.", audio="Nhạc ổn định rồi bắt đầu rút.",
         sci="—", lic="In-house + VNISES."),
    dict(id="SH25", act="VIII · Scientific integrity", vo=["L28", "L29", "L30", "L31", "L32", "L33"], layer="C", assets=["C07"],
         visual="Sơ đồ khái niệm tĩnh, xây theo từng câu: (L29) điểm dữ liệu + nhãn SOURCE; (L30) điểm quan sát đặc vs đường mô phỏng nét đứt; (L31) ranh giới giả định; (L32) vùng ngoài giới hạn gạch chéo + LIMITATIONS; (L33) vùng suy luận mở rộng dần + INFERENCE.",
         motion="Chỉ fade và vẽ nét; không camera move.", trans_in="dip:1.0",
         onscreen="OBSERVATION · DATA · SIMULATION · ASSUMPTION · INFERENCE và SOURCE · CONDITIONS · LIMITATIONS (nhãn nhỏ cạnh từng thành phần).",
         audio="Nhạc rút còn một bè thấp; không âm thanh minh họa.",
         sci="CONCEPTUAL — không có số liệu, không có trục số. Nhãn 'SƠ ĐỒ KHÁI NIỆM' cố định góc trên.",
         lic="In-house."),
    dict(id="SH26", act="VIII · Scientific integrity", vo=["L34", "L35"], layer="B", assets=["B06"],
         visual="Footage thật của VNISES: bảng provenance áp dụng cho mô hình quỹ đạo, rồi cuộn lên chuỗi 'Quan sát → Thay đổi → So sánh → Kiểm chứng → Hiểu'.",
         motion="Phần 1 (0–6,0 s): trượt dọc chậm qua bảng provenance, zoom 1,2. Dissolve 0,8 s. Phần 2: chuỗi 'Quan sát → … → Hiểu', push-in 1,25 → 1,38 — trùng câu 'con đường từ quan sát đến hiểu biết'.", trans_in="dissolve:0.8",
         onscreen="Không.", audio="Nền tối giản.", sci="—", lic="VNISES."),
    dict(id="SH27", act="IX · Những điều chưa biết", vo=["L36", "L37"], layer="A", assets=["A05"],
         visual="Hubble Ultra Deep Field — lần này kéo ra chậm (ngược với SH05), rồi tối dần về đen.",
         motion="Pull-out 1,12 → 1,00; fade to black 1,4 s sau câu L37.", trans_in="dip:1.2",
         onscreen="Không.", audio="Một bè thấp duy nhất; tắt hẳn trước end card.",
         sci="OBSERVATION.", lic="CC BY 4.0 (đã credit ở SH05; credit lại trong end card)."),
    dict(id="SH28", act="X · VNISES", vo=["L38"], layer="C", assets=["C08"],
         visual="Màn đen 1 s im lặng → 'VNISES' → tên đầy đủ → 'vnises.com'. Sau đó thẻ credit hình ảnh.",
         motion="Fade 1,0 s từng dòng. Không chuyển động khác.", trans_in="cut",
         onscreen="VNISES · Vietnam Nexus for Interactive Space Exploration and Science · vnises.com · Credit hình ảnh",
         audio="Im lặng 1 s, sau đó một nốt kết rất nhẹ, tắt dần.",
         sci="—", lic="Credit cho mọi asset CC BY xuất hiện trong phim."),
]

# Shot nào bắt đầu sớm hơn câu VO đầu tiên bao nhiêu giây (mặc định 0,4 s)
SHOT_LEAD = {"SH01": None, "SH11": 0.6, "SH13": 0.9, "SH15": 0.6, "SH16": 0.5, "SH17": 1.2,
             "SH23": 0.8, "SH25": 0.8, "SH27": 0.8, "SH28": 1.2}
